version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    restart: always
    image: node:14
    working_dir: /usr/workspace/clean-node-api
    command: bash -c "npm install --only=prod && npm run debug"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/clean-node-api
    volumes:
      - ./dist/:/usr/workspace/clean-node-api/dist/
      - ./package.json:/usr/workspace/clean-node-api/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo
